# Paths (full paths, no ~)
db_file          "/home/likith/.local/share/mpd/database"
state_file       "/home/likith/.local/share/mpd/state"
playlist_directory "/home/likith/.local/share/mpd/playlists"
sticker_file     "/home/likith/.local/share/mpd/sticker.sql"

# Music directory (full path)
music_directory  "/home/likith/music"

# Logging
log_file         "syslog"

# Auto update and restore
auto_update      "yes"
restore_paused   "yes"

# Socket for systemd user
bind_to_address "127.0.0.1"
port "6600"

# Audio output
audio_output {
    type        "pulse"
    name        "PulseAudio"
}
